#' Binarizing Haplotype Membership Data
#'
#' `binarizeHap()` is binarizing group membership (haplotypes) data into marker
#' like presence / absence of haplotype group per bin.
#' @param hap_mat a matrix of phased group membership (haplotypes) with row
#' corresponding to marker-bins and columns to individuals as generated by
#' `phaseHap()`.
#' @param P1_name a character vector with the name of parent 1
#' @param P2_name a character vector with the name of parent 2
#' @param P1_dosages an integer with haplotypes presence for parent 1. This
#' would be 1 for parent 1 data and 0 for parent 2 data.
#' @param P2_dosages an integer with haplotypes presence for parent 2. This
#' would be 0 for parent 1 data and 1 for parent 2 data.
#'
#' @return a matrix of haplotypes presence /absence with as row haplotypes in
#' physical bins and as columns individuals.
#' @export
#'
#' @examples P1_phased_hap_bin <- binarizeHap(P1_phased_hapmat,
#'   P1_name = "P1",
#'   P2_name = "P2",
#'   P1_dosage = 1,
#'   P2_dosage = 0
#' )
#' @importFrom stats model.matrix as.formula
binarizeHap <- function(hap_mat, P1_name, P2_name, P1_dosages, P2_dosages) {
  hap_df <- as.data.frame(t(hap_mat))
  hap_df[] <- lapply(hap_df, as.factor)
  hap_list <- lapply(colnames(hap_df), function(x) {
    stats::model.matrix(stats::as.formula(paste0("~ ", "`", x, "`", " -1")),
                        hap_df)
  })
  mat <- t(do.call(cbind, hap_list))
  parents <- cbind(
    rep(P1_dosages, times = dim(mat)[1]),
    rep(P2_dosages, times = dim(mat)[1])
  )
  colnames(parents) <- c(P1_name, P2_name)
  mat <- cbind(parents, mat)
  return(mat)
}
