#' Clustering Individuals Based on Distance Matrix
#'
#' `clusterPop()` is a wrapper around stats::hclust() used to cluster
#' individuals based on a list of dissimilarity structure as produced by
#' `getDist()`.
#' It also offers the time consuming option to plot the list of variant matrix
#' clustered per variant and individuals and save the output as pdf.
#' @param dist_list a list of a list of dissimilarity structure of class "dist"
#' as generated by `getDist()`.
#' @param method the agglomeration method to be used. This should be (an
#' unambiguous abbreviation of) one of "ward.D", "ward.D2", "single",
#' "complete", "average" (= UPGMA), "mcquitty" (= WPGMA), "median" (= WPGMC)
#' or "centroid" (= UPGMC).
#' @param plot a logical value indicating if clustered variants matrix should be
#' plotted. Be award that if set to TRUE this will substantially increase
#' running time.
#' @param bins_list the list of variant matrix generated by `makeBins()` and used
#' by `getDist()`. Only necessary if @param plot is set to TRUE.
#' @param pdf_path a character vector with the path to use to save the plots as
#' pdf.
#'
#' @return a list of object of class "hclust" which describes the tree of
#' individuals produced by the clustering process.
#' @export
#'
#' @examples P1_clust_list <- clusterPop(dist_P1_bins, plot = T,
#' bins_list = P1_bins, pdf_path = "./mypop_chr01_P1_clustering.pdf")
#' @importFrom stats hclust
clusterPop <- function(dist_list, method = "ward.D2", plot = F,
                       bins_list = NULL, pdf_path = NULL) {
  hclust <- lapply(dist_list, hclust, method = method)
  if (plot == T) {
    dend <- lapply(lapply(hclust, as.dendrogram), dendextend::set,
      "branches_k_color",
      k = 2
    )
    pdf(pdf_path)
    for (i in seq_along(bins_list))
    {
      if (dim(bins_list[[i]])[1] > 1) {
        heatmap(t(bins_list[[i]]),
          Rowv = dend[[i]],
          Colv = NULL,
          scale = "none",
          labCol = F,
          col = c("pink", "blue"),
          main = names(bins_list)[i]
        )
      }
    }
    dev.off()
  }
  return(hclust)
}
