#' Format Phased Haplotype Membership for SmoothDescent
#'
#'`formatSD()` aggregate P1 and P2 group membership (haplotypes) data generated
#' by OutcrossSeqDiploidR and format it for SmoothDescent.
#' @param P1_hap_mat a matrix of phased group membership (haplotypes) with row
#' corresponding to physical bins and columns to individuals as generated by
#' `phaseHap()` for parent 1.
#' @param P2_hap_mat a matrix of phased group membership (haplotypes) with row
#' corresponding to physical bins and columns to individuals as generated by
#' `phaseHap()` for parent 2.
#' @param P1_name a character vector with the name of parent 1.
#' @param P2_name a character vector with the name of parent 2.
#'
#' @return a list of 3 objects usable as input by SmoothDescent:
#' \itemize{
#'   \item"geno": matrix with markers on the rows, individuals on the columns
#'   with marker names as Rownames. As expected by `smooth_decent()` "geno"
#'   parameter.
#'   \item"hom": matrix with markers on the rows, homologue names on the columns
#'    as expected by `smooth_decent()` "homologue" parameter.
#'   \item"map": data.frame with at a columns "marker" containing marker name
#'   and "position" containing the physical position of the marker. As expected
#'   by `smooth_decent()` "map" parameter.}
#' @export
#'
#' @examples SD_input <- formatSD(P1_phased_hap$hap_mat,
#' P2_phased_hap$hap_mat,
#' P1_name = "P1",
#' P2_name = "P2")
formatSD <- function(P1_hap_mat, P2_hap_mat, P1_name, P2_name) {
  #binarize male and female hap data
  rownames(P1_hap_mat) <- paste(P1_name, rownames(P1_hap_mat),
                                      sep="_")
  rownames(P2_hap_mat) <- paste(P2_name, rownames(P2_hap_mat),
                                sep="_")
  P1_bin <- OutcrossSeqDiploidR::binarizeHap(P1_hap_mat, P1_name, P2_name, 1, 0)
  P2_bin <- OutcrossSeqDiploidR::binarizeHap(P2_hap_mat, P1_name, P2_name, 0, 1)

  #format for SD
  geno <- rbind(P1_bin, P2_bin)

  hom <- matrix(
    data = cbind(
      c(
        rep(c(1, 0), times = nrow(P1_bin) / 2),
        rep(0, times = nrow(P2_bin))
      ),
      c(
        rep(c(0, 1), times = nrow(P1_bin) / 2),
        rep(0, times = nrow(P2_bin))
      ),
      c(
        rep(0, times = nrow(P1_bin)),
        rep(c(1, 0), times = nrow(P2_bin) / 2)
      ),
      c(
        rep(0, times = nrow(P1_bin)),
        rep(c(0, 1), times = nrow(P2_bin) / 2)
      )
    ),
    nrow = nrow(geno), ncol = 4
  )
  rownames(hom) <- rownames(geno)
  colnames(hom) <- c("H1_P1", "H2_P1", "H3_P2", "H4_P2")

  map <- data.frame(
    marker = rownames(hom),
    position = sapply(rownames(hom),
                      function(x) {
                        as.numeric(
                          strsplit(x, "_")[[1]][2]
                        )
                      },
                      simplify = T
    ),
    row.names = NULL
  )
  out <- list(geno = geno,
              hom = hom,
              map = map)
  return(out)
}
