#' Get Distance Between Individuals
#'
#' `getDist()` is a wrapper around stats::dist(). It is applied to a list of
#' matrix to compute distance between individuals based on local variants.
#' @param bins_list a list of matrix as generated by `makeBins()`.
#' @param method the distance measure to be used. This must be one of
#' "euclidean", "maximum", "manhattan", "canberra", "binary" or "minkowski".
#'  Any unambiguous substring can be given.
#'
#' @return a list of dissimilarity structure between individuals in local bins of
#' class "dist".
#' @export
#'
#' @examples dist_P1_bins <- getDist(P1_bins, method = "euclidean")
#' @importFrom stats dist
getDist <- function(bins_list, method = "euclidean") {
  dist <- lapply(lapply(bins_list, t), stats::dist, method = method)
  dist <- lapply(dist, function(x) replace(x, is.na(x),
                                           mean(x[-which(is.na(x))])))
  return(dist)
}
