#' Subdivide Chromosomal Variant Matrix in Bins
#'
#' `makeBins()` subdivide a given chromosomal matrix into a list of bins matrix
#' of given physical length.
#' @param parental_matrix a parent specific chromosomal matrix as generated by
#' `recodeParentMatList()`.
#' @param bin_size an integer with the bin size to use in the same unit as the
#' marker position column of the parental_matrix.
#' @param snp_pos_colname a character vector with the column name of marker
#' position.
#' @return a list of matrix corresponding the subdivision in bins of given
#' physical length of the input chromosomal matrix.
#' @export
#'
#' @examples P1_bins <- makeBins(parent_mat_list[['P1']], bin_size = 100000)
makeBins <- function(parental_matrix, bin_size, snp_pos_colname = "pos") {
  bins_id <- ceiling(parental_matrix[, snp_pos_colname] / bin_size)
  mat <- parental_matrix[, !colnames(parental_matrix) %in% snp_pos_colname]

  bins_list <- split.data.frame(mat, bins_id)


  names(bins_list) <-
    paste0(
      ((as.numeric(names(bins_list)) * bin_size) / 1000000)
      - (bin_size / 1000000),
      "_",
      (as.numeric(names(bins_list)) * bin_size) / 1000000, "_Mb"
    )
  return(bins_list)
}
