#' Phase Local Haplotypes manually
#'
#'`manualPhasing()` is used to manual flip the phasing of a bin and all
#' subsequent bins when, upon visual inspection, a segment was wrongly phased by
#' `phaseHap()`.
#' @param hap_mat a matrix of phased group membership (haplotypes) with row
#' corresponding to physical bins and columns to individuals as generated by
#' `phaseHap()`.
#' @param switch_marker a character vector corresponding to the bin name onward
#' from which phasing need to be flipped. The character vector should be part of
#' `rownames(hap_mat)`.
#' @return a matrix of haplotype with row corresponding to physical bins
#' and columns to individuals with manually corrected phasing.
#' @export
#'
#' @examples P1_phased_hapmat <- manualPhasing(P1_phased_hapmat,"p1_43.9_44_Mb")
#' @importFrom car recode
manualPhasing <- function(hap_mat, switch_marker) {
  pos_switch <- which(rownames(hap_mat) == switch_marker)
  flip <- hap_mat[pos_switch:nrow(hap_mat), ]
  flip <- t(apply(flip,
    MARGIN = 1,
    FUN = function(x) car::recode(x, "1=2; 2=1")
  ))
  mat <- rbind(hap_mat[1:pos_switch - 1, ], flip)
  return(mat)
}
