#' Phase Local Haplotypes to Minimize Recombination Frequency
#'
#' `phaseHap()` is calculating recombination frequencies between physically
#' adjacent bins and minimize them by flipping the haplotype phasing if
#' necessary.
#' After a first round of phasing with `phaseHap()`, it is advised to visualize
#' the output, remove bins with aberrant haplotype data and, manually correct
#' phasing using `manualPhasing()` if necessary.
#' @param hap_list a list of vector corresponding to marker-bins with group
#' membership corresponding to local haplotypes as generated by `getHap()` and
#' preferably filtered using the information generated by `qualCheck()`.
#'
#' @return  a list of 2 elements:
#' \itemize{
#'   \item "hap_mat" a matrix of phased group membership (haplotypes) with row
#' corresponding to marker-bins and columns to individuals.
#'   \item "recoded" a vector of logical values the same length as "hap_list"
#' indicating if the given bin phasing was flipped.}
#' @export
#'
#' @examples
#' P1_phased_hap <- phaseHap(P1_hap_list[P1_flt_bins])
phaseHap <- function(hap_list) {
  recoded <- vector(length = length(hap_list))
  names(recoded) <- names(hap_list)
  recoded[[1]] <- F

  for (i in seq(2, length(hap_list)))
  {
    rec <- sum(abs((hap_list[[i]] - hap_list[[i - 1]])))
    if (rec > length(hap_list[[i]]) - rec) {
      hap_list[[i]] <- car::recode(hap_list[[i]], "1=2; 2=1")
      recoded[[i]] <- T
    } else {
      recoded[[i]] <- F
    }
  }
  out_list <- list(
    hap_mat = t(do.call(cbind,hap_list)),
    recoded = recoded
  )
  return(out_list)
}
